"""empty message

Revision ID: 86aae79bedd3
Revises: dbfba0a8629c
Create Date: 2024-09-13 11:18:51.865669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86aae79bedd3'
down_revision = 'dbfba0a8629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
