"""empty message

Revision ID: 982ed25ba02f
Revises: d9fd1c7d6ad6
Create Date: 2024-09-13 06:46:48.638651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982ed25ba02f'
down_revision = 'd9fd1c7d6ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_test', sa.String(length=100), nullable=False),
    sa.Column('desc_test', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenda')
    # ### end Alembic commands ###
