"""empty message

Revision ID: ce80f2065fca
Revises: 86aae79bedd3
Create Date: 2024-09-14 02:12:44.183516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce80f2065fca'
down_revision = '86aae79bedd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title_test', sa.String(length=100), nullable=False),
    sa.Column('desc_test', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.drop_table('tenda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenda',
    sa.Column('title_test', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc_test', sa.VARCHAR(length=400), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False)
    )
    op.drop_table('testing')
    # ### end Alembic commands ###
