"""empty message

Revision ID: dbfba0a8629c
Revises: 283e9572d277
Create Date: 2024-09-13 10:45:09.251472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfba0a8629c'
down_revision = '283e9572d277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tenda')
    with op.batch_alter_table('tenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('task_id')

    op.create_table('_alembic_tmp_tenda',
    sa.Column('title_test', sa.VARCHAR(length=100), nullable=False),
    sa.Column('desc_test', sa.VARCHAR(length=400), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
