"""empty message

Revision ID: f1b71c4859da
Revises: ce80f2065fca
Create Date: 2024-09-16 03:08:39.047449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b71c4859da'
down_revision = 'ce80f2065fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('title_test', sa.VARCHAR(length=100), nullable=False),
    sa.Column('desc_test', sa.VARCHAR(length=400), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###
